# Generated by Django 3.1.7 on 2021-04-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanagedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddDonors',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
                ('cardno', models.CharField(max_length=100)),
                ('cvv', models.CharField(max_length=100)),
                ('expirydate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AddEvents',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('eventtype', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('eventdate', models.CharField(max_length=100)),
                ('eventtime', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('organizer', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NewOrphan',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('childimage', models.ImageField(upload_to='childimages/')),
                ('orphanid', models.CharField(max_length=100)),
                ('dateofjoining', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('haircolor', models.CharField(max_length=100)),
                ('eyecolor', models.CharField(max_length=100)),
                ('otherdescription', models.CharField(max_length=100)),
                ('y1', models.CharField(max_length=100)),
                ('y2', models.CharField(max_length=100)),
                ('y3', models.CharField(max_length=100)),
                ('y4', models.CharField(max_length=100)),
                ('y5', models.CharField(max_length=100)),
                ('otherdescriptions', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NewRegister',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('confirm', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
    ]
