# Generated by Django 3.1.7 on 2021-04-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanagedata', '0002_adddonors_addevents_neworphan_newregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestChildren',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('user_image', models.ImageField(upload_to='requestedchild/')),
                ('child_id', models.CharField(max_length=100)),
                ('orphanid', models.CharField(max_length=100)),
                ('orphan_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='newregistration',
            name='image',
            field=models.ImageField(upload_to='userimages/'),
        ),
    ]
