# Generated by Django 3.1.7 on 2021-05-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orphanagedata', '0004_auto_20210501_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newregistration',
            old_name='userimages',
            new_name='user_image',
        ),
    ]
