# Generated by Django 3.1.7 on 2021-05-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanagedata', '0005_auto_20210501_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='addevents',
            name='eventimg',
            field=models.ImageField(default=1, upload_to='eventimages/'),
            preserve_default=False,
        ),
    ]
